"""init: create questions table

Revision ID: 2848b7ef1c65
Revises:
Create Date: 2026-07-26 10:07:35.372441

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2848b7ef1c65"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question",
        sa.Column("id", sa.String(length=12), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("tags", sa.String(length=500), nullable=False),
        sa.Column("difficulty", sa.String(length=20), nullable=False),
        sa.Column("answer", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("question")
    # ### end Alembic commands ###
